CREATE TABLE PLATAFORMA (
    ID_PLATAFORMA SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL UNIQUE, --  2) UNIQUE: Garante que não existam plataformas com nomes duplicados
    DESCRICAO VARCHAR(50),
    OBSERVACAO VARCHAR(50)
);

CREATE TABLE USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    LOGIN VARCHAR(50) NOT NULL UNIQUE, --  2) UNIQUE: O login deve ser exclusivo para cada usuário
    SENHA VARCHAR(50) NOT NULL
);

CREATE TABLE JOGO (
    ID_JOGO SERIAL PRIMARY KEY,
    TITULO VARCHAR(150) NOT NULL,
    GENERO VARCHAR(50) NOT NULL,
    ID_PLATAFORMA INT NOT NULL,
    ANO_LANCAMENTO INT NOT NULL,
    HORAS_JOGADAS DECIMAL(5,2) DEFAULT 0,
    
    --  1) CHECK: Impede que o ano de lançamento seja um valor irreal (ex: futuro distante ou negativo)
    CONSTRAINT CHK_ANO_LANCAMENTO CHECK (ANO_LANCAMENTO > 1950),
    
    CONSTRAINT FK_JOGO_PLATAFORMA 
        FOREIGN KEY (ID_PLATAFORMA) REFERENCES PLATAFORMA (ID_PLATAFORMA)
        ON DELETE RESTRICT --  4) ON DELETE: Impede apagar uma plataforma que possui jogos vinculados
);

CREATE TABLE COLECAO (
    ID_COLECAO SERIAL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATA_CRIACAO DATE NOT NULL DEFAULT CURRENT_DATE, --  3) DEFAULT: Preenche automaticamente com a data de hoje
    ID_USUARIO INT NOT NULL,
    
    CONSTRAINT FK_COLECAO_USUARIO 
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
		ON DELETE CASCADE --  4) ON DELETE: Se o usuário for deletado, suas coleções também serão
);

CREATE TABLE USUARIO_JOGO (
    ID_USUARIO INT NOT NULL,
    ID_JOGO INT NOT NULL,
    DATA_INICIO DATE NOT NULL DEFAULT CURRENT_DATE, --  3) DEFAULT: Data de início padrão é o dia do registro
    DATA_FIM DATE,
    AVALIACAO INT NOT NULL,
    STATUS INT NOT NULL, 
   
    PRIMARY KEY (ID_USUARIO, ID_JOGO),
    
    --  1) CHECK: Garante que a avaliação esteja em um intervalo de 0 a 10
    CONSTRAINT CHK_AVALIACAO CHECK (AVALIACAO BETWEEN 0 AND 10),
    
    --  1) CHECK: Valida status permitidos (ex: 1-Planejado, 2-Jogando, 3-Concluído)
    CONSTRAINT CHK_STATUS CHECK (STATUS IN (1, 2, 3)),

    CONSTRAINT FK_USUARIO_JOGO_USUARIO 
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
		ON DELETE CASCADE,
    CONSTRAINT FK_USUARIO_JOGO_JOGO 
        FOREIGN KEY (ID_JOGO) REFERENCES JOGO (ID_JOGO)
		ON DELETE CASCADE
);